title: GTFOBins

baseurl: /new # TODO temporary

exclude:
  - /Dockerfile
  - /LICENSE
  - /Makefile
  - /README.md
  - /linter/

permalink: pretty

collections:
  gtfobins:
    output: true

defaults:
  - scope:
      path: _gtfobins
    values:
      layout: gtfobin
