---
title: GTFOBins

exclude:
  - '/Gemfile'
  - '/LICENSE'
  - '/Makefile'
  - '/README.md'
  - '/scripts'

permalink: pretty

collections:
  gtfobins:
    output: true

defaults:
  - scope:
      path: '_gtfobins'
    values:
      layout: gtfobin
